const ADMIN_SETTING_TYPE = {
    MAX_INTERESTED_RATE:1,
    MIN_INTERESTED_RATE:2,
    MIN_LENDING_EXPECTED_MONEY:3,
    MIN_INVEST_MONEY:4,
    DISCOUNT_RATE:5,
    DEFAULT_LIMIT_MONEY_FOR_NEW_MEMBER:6
    
}
module.exports.ADMIN_SETTING_TYPE = ADMIN_SETTING_TYPE;