
const NOTIFICATION_TYPE = {
    SYSTEM:0,
    ACCOUNT_HISTORY:1,
    INVEST_REQUEST:2,
    BORROW_REQUEST:3,
    ACCOUNT:4,
    WIDTHDRAW_REQUEST: 5
}
module.exports.NOTIFICATION_TYPE = NOTIFICATION_TYPE;